version: "3.9"
services:
  firebase:
    container_name: firebase
    env_file: .env
    build:
      context: .
      dockerfile: container/firebase/Dockerfile
    volumes:
      - ./container/firebase/:/opt/workspace:cached
    ports:
      - "9099:9099"
      - "9199:9199"
      - "4400:4400"
      - "4500:4500"
      - "4000:4000"
    working_dir: /opt/workspace
    command: ['firebase', 'emulators:start', '--import=./.emulator']
    # if you want to export data when container is stopped, use this command
    # command: ['firebase', 'emulators:start', '--export-on-exit', '--import=./.emulator']
    tty: true
